shu-etal replication notebook
LivingPark-MRI/shu-etal pull request #1
Opened 2022-08-19 21:39 UTC by mohanadarafe

2022-08-22 08:44 UTC, glatard commented
Hi @mohanadarafe, great work, I only added a few suggestions to add more explanation to the notebook text. It would be nice to read the notebook again and add as many explanations as possible to the text, to make sure it's readable by someone who would skip the code.

2022-08-22 08:45 UTC, glatard requested changes
Install.log shouldnt be committed.

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +    "LivingPark notebooks use a *cache* directory to store analysis inputs and outputs. Inputs typically include PPMI Study Data and imaging data whereas outputs include processed images and other de
The cache directory currently isn't functional, let's update this comment accordingly.

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +    "We will also need file `MRI_info.csv` and `MDS_UPDRS_Part_III_clean_v0.1.csv` that are produced by another LivingPark notebook available at https://github.com/LivingPark-MRI/ppmi-MRI-metadata. T
Add link to other notebook too.

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +    "The first dataframe required will be extracted from `MDS_UPDRS_Part_III_clean.csv` with the objective to select a group of patients that are off medication on the day their exam was taken."
not "on the day" but rather "during examination".

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +     },
I'd be great to add a line to explain what this histogram is and to add axes titles.
Also, all the merging could be done in 1 cell.

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +    "Ensure that the cohort built does not have any defects (duplication, size, etc..)"
List these issues explicitly in the text.

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +    "       f\"\\t\\t\\t Stage 3 \\t| {len(stable[stable['NHY_x']=='3'])} \\t\\t\\t| {len(progr[progr['NHY_x']=='3'])}\"\n",
Improve table formatting by putting the numbers in a dataframe. See cell 8 in https://github.com/LivingPark-MRI/scherfler-etal/blob/main/scherfler-etal.ipynb

2022-08-22 08:45 UTC, glatard commented on shu-etal.ipynb
> +    "This study recruited 72 patients with progressive PD and 72 patients with stable PD matched by age, sex and category of HYS. This following population from PPMI was used:\n",
notebook intro should explain briefly what the replicated paper did and what was the main result

2022-08-25 13:23 UTC, mohanadarafe commented
@glatard Thank you for the review, I updated the notebook accordingly. Let me know if it needs anything else!

2022-08-25 13:28 UTC, merged